#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Suzuha Kiuchi
# SPDX-License-Identifier: BSD-3-Clause
import sys
import math


def tonum(s):
    try:
        return int(s)
    except:
        return float(s)


total = 0
count = 0
maxvalue = None
minvalue = None
values = []
for line in sys.stdin:
    line = line.rstrip()
    num = tonum(line)
    total += num
    count += 1
    if maxvalue is None or maxvalue < num:
        maxvalue = num
    if minvalue is None or minvalue > num:
        minvalue = num
    values.append(num)


avg = total / count
sum_sq = 0
for x in values:
    sum_sq += (x - avg) ** 2


var = sum_sq / count
std = math.sqrt(var)

#出力
results = []
output_arg = sys.argv[1:]
if not output_arg:
    output_arg = ["avg", "max", "min", "var", "std"]
if "平均値" in output_arg or "avg" in output_arg:
    results.append('{:.2f}'.format(avg))
if "最大値" in output_arg or "max" in output_arg:
    results.append(maxvalue)
if "最小値" in output_arg or "min" in output_arg:
    results.append(minvalue)
if "分散" in output_arg or "var" in output_arg:
    results.append('{:.2f}'.format(var))
if "標準偏差" in output_arg or "std" in output_arg:
    results.append('{:.2f}'.format(std))


print(*results)
